#
#   Exercise 2  Makefile
#
#   AUTHORS     Marvin Kropp
#               Johannes Haux
#               Christoph Klein
#

CC = g++
CFLAGS = -Wall
TEXC = pdflatex
DOCUNAME = docu_2

docu:
	$(TEXC) $(DOCUNAME).tex

clean:
	rm -f   $(DOCUNAME).pdf $(DOCUNAME).toc $(DOCUNAME).aux $(DOCUNAME).log
